"""initial

Revision ID: 21e5d9e28a68
Revises:
Create Date: 2026-06-29 10:54:07.882537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21e5d9e28a68"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name_he", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("name_fr", sa.String(), nullable=True),
        sa.Column("name_ru", sa.String(), nullable=True),
        sa.Column("name_es", sa.String(), nullable=True),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("firebase_uid", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("preferred_lang", sa.String(length=5), nullable=True),
        sa.Column("preferred_currency", sa.String(length=3), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("saved_card_last4", sa.String(length=4), nullable=True),
        sa.Column("saved_card_brand", sa.String(), nullable=True),
        sa.Column("has_saved_card", sa.Boolean(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
    op.create_table(
        "prayers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("title_he", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("title_fr", sa.String(), nullable=True),
        sa.Column("title_ru", sa.String(), nullable=True),
        sa.Column("title_es", sa.String(), nullable=True),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("body_he", sa.Text(), nullable=True),
        sa.Column("body_en", sa.Text(), nullable=True),
        sa.Column("body_fr", sa.Text(), nullable=True),
        sa.Column("body_ru", sa.Text(), nullable=True),
        sa.Column("body_es", sa.Text(), nullable=True),
        sa.Column("body_ar", sa.Text(), nullable=True),
        sa.Column("seo_keywords_he", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("seo_keywords_en", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("seo_description_he", sa.Text(), nullable=True),
        sa.Column("seo_description_en", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prayers_slug"), "prayers", ["slug"], unique=True)
    op.create_table(
        "quick_buttons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("prayer_id", sa.UUID(), nullable=True),
        sa.Column("label_he", sa.String(), nullable=True),
        sa.Column("label_en", sa.String(), nullable=True),
        sa.Column("label_fr", sa.String(), nullable=True),
        sa.Column("label_ru", sa.String(), nullable=True),
        sa.Column("label_es", sa.String(), nullable=True),
        sa.Column("label_ar", sa.String(), nullable=True),
        sa.Column("default_amount_ils", sa.Integer(), nullable=True),
        sa.Column("default_amount_usd", sa.Integer(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prayer_id"],
            ["prayers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "recurring_donations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("prayer_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("next_charge_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["prayer_id"],
            ["prayers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "donations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("prayer_id", sa.UUID(), nullable=False),
        sa.Column("quick_button_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("donor_name", sa.String(), nullable=False),
        sa.Column("prayer_name", sa.String(), nullable=True),
        sa.Column("donor_note", sa.String(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column("receipt_email", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["prayer_id"],
            ["prayers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quick_button_id"],
            ["quick_buttons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("donations")
    op.drop_table("recurring_donations")
    op.drop_table("quick_buttons")
    op.drop_index(op.f("ix_prayers_slug"), table_name="prayers")
    op.drop_table("prayers")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
